{
 "title": "RC Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(system_cpu_usage,application)"
    }
   },
   {
    "name": "quantile",
    "query": "0.001, 0.01, 0.1, 0.25, 0.50, 0.75, 0.95, 0.99, 0.999, 1"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(application) (\n  rate(http_server_requests_seconds_count{application=~\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "TOTAL RPS"
    }
   ]
  },
  {
   "title": "HTTP Req Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(application) (http_server_requests_seconds_sum{application=~\"$service\"}) / sum by(application) (http_server_requests_seconds_count{application=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=~\"$service\"}",
     "legendFormat": "{{application}} |{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=~\"$service\"}",
     "legendFormat": "{{application}} |{{instance}} | {{area}} | {{id}}"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(application, method) (\n  rate(realtorconnect_auth_login_total{application=~\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "{{application}} | AuthService.{{method}}"
    },
    {
     "expr": "sum by(application, method) (\n  rate(realtorconnect_user_service_total{application=~\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "{{application}} | UserService.{{method}}"
    },
    {
     "expr": "sum by(application, method) (\n  rate(realtorconnect_realtor_service_total{application=~\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "{{application}} | RealtorService.{{method}}"
    },
    {
     "expr": "sum by(application, method) (\n  rate(realtorconnect_realEstate_service_total{application=~\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "{{application}} | RealEstateService.{{method}}"
    },
    {
     "expr": "sum by(application, method) (\n  rate(realtorconnect_realEstatePhoto_service_total{application=~\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "{{application}} | RealEstatePhotoService.{{method}}"
    },
    {
     "expr": "sum by(application, method) (\n  rate(realtorconnect_file_service_total{application=~\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "{{application}} | FileService.{{method}}"
    },
    {
     "expr": "sum by(application, method) (\n  rate(realtorconnect_contact_service_total{application=~\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "{{application}} | ContactService.{{method}}"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${quantile:raw}, sum by(application, method, le) (rate(realtorconnect_auth_login_seconds_bucket{application=~\"$service\"}[$__rate_interval])))",
     "legendFormat": "{{application}} | AuthService.{{method}}"
    },
    {
     "expr": "histogram_quantile(${quantile:raw}, sum by(application, method, le) (rate(realtorconnect_user_service_seconds_bucket{application=~\"$service\"}[$__rate_interval])))",
     "legendFormat": "{{application}} | UserService.{{method}}"
    },
    {
     "expr": "histogram_quantile(${quantile:raw}, sum by(application, method, le) (rate(realtorconnect_realtor_service_seconds_bucket{application=~\"$service\"}[$__rate_interval])))",
     "legendFormat": "{{application}} | RealrorService.{{method}}"
    },
    {
     "expr": "histogram_quantile(${quantile:raw}, sum by(application, method, le) (rate(realtorconnect_realEstate_service_seconds_bucket{application=~\"$service\"}[$__rate_interval])))",
     "legendFormat": "{{application}} | RealEstateService.{{method}}"
    },
    {
     "expr": "histogram_quantile(${quantile:raw}, sum by(application, method, le) (rate(realtorconnect_realEstatePhoto_service_seconds_bucket{application=~\"$service\"}[$__rate_interval])))",
     "legendFormat": "{{application}} | RealEstatePhotoService.{{method}}"
    },
    {
     "expr": "histogram_quantile(${quantile:raw}, sum by(application, method, le) (rate(realtorconnect_file_service_seconds_bucket{application=~\"$service\"}[$__rate_interval])))",
     "legendFormat": "{{application}} | FileService.{{method}}"
    },
    {
     "expr": "histogram_quantile(${quantile:raw}, sum by(application, method, le) (rate(realtorconnect_contact_service_seconds_bucket{application=~\"$service\"}[$__rate_interval])))",
     "legendFormat": "{{application}} | ContactService.{{method}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "API Responses By Status Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(status, uri) (\n  rate(http_server_requests_seconds_count{application=~\"$service\", uri!~\".*swagger.*\", uri!=\"/\", uri!=\"/**\", uri!=\"/v3/api-docs/{group}\", uri!~\".*actuator.*\"}[$__rate_interval])\n)",
     "legendFormat": "uri: {{uri}} | status: {{status}}"
    }
   ]
  },
  {
   "title": "API Responses By Status Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(uri, status) (http_server_requests_seconds_sum{application=~\"$service\", uri!~\".*swagger.*\", uri!=\"/\", uri!=\"/**\", uri!=\"/v3/api-docs/{group}\", uri!~\".*actuator.*\"}) / sum by(uri, status) (http_server_requests_seconds_count{application=~\"$service\", uri!~\".*swagger.*\", uri!=\"/\", uri!=\"/**\", uri!=\"/v3/api-docs/{group}\", uri!~\".*actuator.*\"})",
     "legendFormat": "uri: {{uri}} | status: {{status}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=~\"$service\"}",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Threads States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=~\"$service\"}",
     "legendFormat": "{{application}} | {{state}}"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{application=~\"$service\"}",
     "legendFormat": "{{application}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Data JPA Top 25 Slowest Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(25, max by (repository, method) (spring_data_repository_invocations_seconds_max{application=~\"$service\"}))",
     "legendFormat": "{{repository}}.{{method}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=~\"$service\"}",
     "legendFormat": "{{application}} | active"
    },
    {
     "expr": "hikaricp_connections_idle{application=~\"$service\"}",
     "legendFormat": "{{application}} | idle"
    }
   ]
  },
  { "title": "Email", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "AVG Send Email Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${quantile:raw}, avg by (application, instance, le) (rate(email_sender_service_seconds_bucket{application=~\"$service\", method=\"send\"}[$__rate_interval])))",
     "legendFormat": "{{application}} | {{instance}}"
    }
   ]
  },
  {
   "title": "RPM by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum by(application, instancem, status) (increase(email_processor_count_total[1m]))",
     "legendFormat": "{{application}} | {{instance}} | {{status}}"
    }
   ]
  },
  {
   "title": "Sending RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by(application, instance) (increase(email_sender_service_seconds_count[$__rate_interval]))",
     "legendFormat": "{{application}} | {{instance}}"
    }
   ]
  },
  {
   "title": "AVG Process Emails Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${quantile:raw}, avg by (application, instance, le) (rate(email_processor_service_seconds_bucket{application=~\"$service\"}[$__rate_interval])))",
     "legendFormat": "{{application}} | {{instance}}"
    }
   ]
  }
 ]
}