events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=5s ipv6=off;

    server {
        listen 8080;

        set $operational_service http://operational-service:8080;
        set $real_estate_service http://real-estate-service:8080;
        set $user_service http://user-service:8080;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /api/auth {
            proxy_pass $user_service;
        }

        location /api/users {
            proxy_pass $user_service;
        }

        location ~ ^/api/realtors/real-estates {
            proxy_pass $real_estate_service;
        }

        location ~ ^/api/realtors/[0-9]+/real-estates {
            proxy_pass $real_estate_service;
        }

        location /api/realtors {
            proxy_pass $user_service;
        }

        location /api/admins {
            proxy_pass $operational_service;
        }

        location /api/admin-panel {
            proxy_pass $operational_service;
        }

        location /api/settings {
            proxy_pass $operational_service;
        }

        location /actuator {
            proxy_pass $operational_service;
        }

        location / {
            proxy_pass $operational_service;
        }
    }
}
