global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: operational-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names:
          - operational-service
        type: A
        port: 8080

  - job_name: user-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names:
          - user-service
        type: A
        port: 8080

  - job_name: real-estate-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names:
          - real-estate-service
        type: A
        port: 8080

  - job_name: email-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names:
          - email-service
        type: A
        port: 8090
