spring:
  application:
    name: email-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${spring.application.name}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true

email:
  server:
    credentials:
      username: ${EMAIL_USERNAME}
      password: ${EMAIL_PASSWORD}
    network:
      host: smtp.gmail.com
      port: 587
    properties:
      mail.protocol: smtp
      mail.test-connection: true
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  debugMode:
    enabled: ${DEBUG_EMAIL_ENABLED:false}
    from: info@realtorconnect.com
    server:
      credentials:
        username: user
        password: user
      network:
        host: localhost
        port: 1025
  processor:
    processing-delay-ms: 1000
    batch-size: 50
