spring:
  application:
    name: email-service

email:
  server:
    credentials:
      username: ''
      password: ''
    network:
      host: smtp.gmail.com
      port: 587
    properties:
      mail.protocol: smtp
      mail.test-connection: true
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  debugMode:
    enabled: false
    from: info@realtorconnect.com
    server:
      credentials:
        username: user
        password: user
      network:
        host: localhost
        port: 1025
  processor:
    processing-delay-ms: 1000
    batch-size: 10
